name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install -e . --system
        uv pip install -e ".[dev]" --system`
    - name: Analysing the code with pytest
      run: |
        pytest -vvvv  --cov=AnglE tests/
